/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jarEncoder_ByteCodeEncryptor */

#ifndef _Included_org_jarEncoder_ByteCodeEncryptor
#define _Included_org_jarEncoder_ByteCodeEncryptor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jarEncoder_ByteCodeEncryptor
 * Method:    encrypt
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_jarEncoder_ByteCodeEncryptor_encrypt
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
const int compare_length = 8;
const char* package_prefix= "javaTest";
#endif
#endif
